<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ronan
 * Date: Mon, 16 Jan 2012 19:44:08 +0100
 */

$conf['title'] = 'Torch7';
$conf['start'] = 'index';
$conf['template'] = 'torch7';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = 1;
$conf['useslash'] = 1;
$conf['basedir'] = '/';

// end auto-generated content
