#!/bin/sh

ln -s /remote/torch7/dok /var/lib/dokuwiki/data/pages/manual
ln -s /remote/torch7/dokmedia /var/lib/dokuwiki/data/media/manual
ln -s /remote/torch7/index.txt /var/lib/dokuwiki/data/pages/index.txt
